const B = import.meta.env.BASE_URL;
const pages = (start, end, labels) => Array.from({length:end-start+1}, (_,i)=>({number:start+i, src:`${B}portfolio/page-${String(start+i).padStart(2,'0')}.jpg`, caption:labels[i]}));
const shots = (prefix, labels, v) => labels.map((caption,i)=>({number:i+1, src:`${B}portfolio/${prefix}-${String(i+1).padStart(2,'0')}.jpg${v?`?v=${v}`:''}`, caption}));
const cryingCenterPages = ['项目概述与正面入口','灵感来源与造型演绎','情绪主题与入口意象','平面、分区与立面图纸','陈列展示与品牌影像','试衣区与休憩洽谈区'].map((caption,i)=>({number:i+1,src:`${B}portfolio/crying-center/crying-center-${String(i+1).padStart(2,'0')}.png`,caption}));

export const projects = [
  {id:'04', category:'VILLAGE / LANDSCAPE', name:'裕固族村落复兴计划', subtitle:'建筑、景观与地方产业的共同更新', image:B+'portfolio/project-04.jpg', color:'#73866e', tags:['乡村更新','景观规划','文化传承'], summary:'从当地居民的生产生活出发，探索裕固族村落的复兴路径。', detail:'以大草滩村为研究对象，将建筑景观改造与当地产业相结合。方案围绕居民生活方式和裕固族文化，展开住居、羊圈、村落规划与产业布局设计，探索传统牧业与当代生活的连接。', pages:pages(4,9,['项目概述','区位、气候与植被分析','居民分析与复兴策略','居住与羊圈设计','村落规划','产业布局与交互设计'])},
  {id:'07', category:'ARCHITECTURE / EXPERIENCE', name:'中医药文化体验空间设计', subtitle:'将文化概念转译为可感知的空间', image:B+'portfolio/project-07.jpg', color:'#4b514c', tags:['文化空间','建筑设计','沉浸体验'], summary:'在景观与建筑之间，构建中医药文化的体验场所。', detail:'选址于峨眉山市市区，以《伤寒杂病论》的六经理论作为设计灵感。地上空间承载陈列、展览与学习，地下空间通过构筑物与参观流线，将文化概念转化为沉浸式空间体验。', pages:pages(10,15,['项目概述','文化、区位与地理分析','设计策略与形态推演','地下空间与构筑物设计','平面、流线与空间结构','结构爆炸图与场景渲染'])},
  {id:'05', category:'PUBLIC SPACE / INTERACTION', name:'南京云锦主题文化广场', subtitle:'让非遗进入城市的公共生活', image:B+'portfolio/project-05.jpg', color:'#d7a16c', tags:['公共空间','非遗文化','互动装置'], summary:'以南京云锦为线索，探索非遗文化在城市公共空间中的表达。', detail:'围绕南京鼓楼广场展开设计，以互动装置、小型展览空间与参观体验，呈现云锦的织造技艺与文化。通过空间展示和互动方式，建立公众与非遗之间更直接的连接。', pages:pages(16,20,['项目概述','背景、场地与功能分析','设计策略与总体布局','参观体验与模型制作','互动演示与装置效果'])},
  {id:'06', category:'INTERIOR / WORKPLACE', name:'绿意未来办公室设计', subtitle:'在办公与生态之间，寻找平衡', image:B+'portfolio/project-06.jpg', color:'#658f85', tags:['室内设计','旧厂改造','生态办公'], summary:'以旧厂房更新为起点，设计融入生态体验的办公环境。', detail:'方案面向武汉市硚口区创意园区的床单厂改造，将两层建筑组织为接待、展览、办公与阅读等空间。通过生态角、动静分区与人员分流，回应办公活动中的交流与专注需求。', pages:pages(21,25,['项目概述','空间概念与整体表达','平面与立面图纸','场地、行为与设计策略','办公空间与场景渲染'])},
  {id:'10', category:'RETAIL / INTERIOR', name:'哭喊中心服装店空间设计', subtitle:'以黑白灰构成情绪释放与个性共鸣的零售体验', image:B+'portfolio/crying-center/crying-center-01.png', color:'#5b5b5b', tags:['零售空间','品牌体验','室内设计'], summary:'以品牌符号为起点，构建兼具时尚、艺术与情感表达的服装店体验。', detail:'项目占地约 22×20×4m，总面积 440㎡。设计从 Crying Center 品牌标识的 C 形波浪与弧线中提取空间语言，以黑、白、灰为主色调，组织收银、购物、试衣、咨询、休憩与陈列区域，并通过回游动线和弧形展台，让顾客在挑选衣物的过程里获得具有个性与共鸣感的品牌体验。', pages:cryingCenterPages},
  {id:'08', category:'SERVICE / SOCIAL SPACE', name:'Serendpia 城市社交空间布局系统', subtitle:'为城市中的相遇，提供新的可能', image:B+'portfolio/project-08.jpg', color:'#c79193', tags:['服务设计','移动空间','用户体验'], summary:'以“第三空间”为出发点，探索适合年轻人的移动社交空间。', detail:'围绕年轻人的社交压力与日常出行场景，将移动空间、用户旅程和活动布局结合。通过空间组合与服务流程，让用户获得不同于家庭与工作场所的交流选择。', pages:pages(27,30,['设计背景与第三空间概念','用户研究与场景分析','空间发展与布局方案','服务流程与设计表达'])},
  {id:'09', category:'PRODUCT / SYSTEM', name:'UR-CLEANER 水上清洁系统', subtitle:'让干净的水面，连接更智能的城市', image:B+'portfolio/project-09.jpg', color:'#5d513e', tags:['产品设计','系统设计','三维表达'], summary:'围绕水域清洁场景，探索自动垃圾收集与配套回收系统。', detail:'方案包括水上垃圾收集机器人、中央处理仓与配套作业流程，展示产品造型、系统关系、回收细节与尺寸设计。以模块化和智能控制为设计方向，回应不同水域的清洁需求。', pages:pages(31,34,['产品概念与整体造型','中央处理仓与系统关系','作业流程与回收细节','尺寸与设计参数'])},
  {id:'02', category:'AI VIDEO / ADVERTISING', name:'满分魅力挑战 · AI创意广告视频', subtitle:'HBN 咖啡因眼霜的 AI 生成创意视频', image:B+'portfolio/project-02.jpg', color:'#c98d90', tags:['AI视频','创意广告','AIGC工作流'], summary:'以游戏化叙事，把产品卖点讲成一场逆袭故事。', detail:'为 HBN 咖啡因眼霜策划的 AI 生成创意广告《满分魅力挑战》。面向 18–35 岁初老人群，以「游戏化护肤」为核心，将产品包装为换装 PK 中的「SSS 级急救装备」：主角落败后激活眼霜，触发细胞战场特效，以满分魅力逆袭。全流程使用 Midjourney、即梦、Vidu 生成角色、场景与特效，配合 8bit 音乐与剪映合成，完成从情绪板、故事脚本、分镜表到成片的完整视频创作。', pages:shots('video',['作品封面','产品信息与目标群体','情绪板','创意阐述','故事脚本','分镜表（一）','分镜表（二）','AI工具与关键词','定稿分镜（一）','定稿分镜（二）','角色与弹窗生成','角色场景一致性','场景生成步骤解析','音乐与音效风格','合成剪辑','成片展示'])},
  {id:'03', category:'AI ILLUSTRATION / BOOK', name:'湿地四季 · AI儿童科普绘本', subtitle:'面向 6–12 岁儿童的湿地生态绘本', image:B+'portfolio/project-03.jpg', color:'#669083', tags:['AI绘本','科普插画','AIGC工作流'], summary:'用统一的 AI 画风，为孩子画出湿地的四季。', detail:'《湿地四季》是一套面向 6–12 岁儿童的湿地生态科普绘本。以角色扮演方式驱动 LLM 生成约 15,000 字、35+ 场景文本，再以「铅笔手绘 × 梵高笔触 × 怀旧印刷 × 绿色基调」的统一风格关键词，通过 --sref 批量生成春、夏、秋、冬四季共 32+ 幅风格一致的插画，并将科学常识、历史文化与环保意识贯穿全书。', pages:shots('wetland',['绘本封面','主题价值与目标','项目总览','文本生成 · Prompt 策略','核心风格提示词','风格迭代与四季温度策略','春季篇章 · 万物复苏（一）','春季篇章 · 万物复苏（二）','夏季篇章 · 生机盎然','秋季篇章 · 金色画卷','冬季篇章 · 静谧之美'])},
  {id:'01', category:'NEW MEDIA / OPERATIONS', name:'新媒体运营实践', subtitle:'政务新媒体运营与个人账号矩阵', image:B+'portfolio/project-01.jpg', color:'#5e7fa3', tags:['新媒体运营','公众号排版','活动拍摄','账号矩阵'], summary:'从政务平台到个人账号，把内容做成持续的连接。', detail:'包含两段运营实践：在共青团宜昌市委员会宣传部，负责「青春宜昌」公众号推文的内容撰写与排版，累计阅读量 2000+、点赞 100+，并参与 5 场活动的现场执行、全程影像拍摄与素材整理；同时运营小红书、抖音个人矩阵账号，以二次元垂类内容（漫展、谷子、cos）为主，累计获赞 2900+，单条最高播放 2.1 万。', pages:shots('media',['新媒体运营 · 封面','「青春宜昌」公众号推文策划运营','活动现场拍摄与素材整理','个人账号运营 · 小红书/抖音'],2)},
];
